### ISSUE TITLE
Use progressive as fallback URL

### ISSUE THREAD

**Issue by goatandsheep** [bitmovin/bitmovin-javascript#103]
I need to have an mp4 fallback URL for when my HLS / Dash players don't work for the following errors:

* `SOURCE_COULD_NOT_LOAD_MANIFEST` (if I put a link with a typo)
* `SOURCE_NO_SUPPORTED_TECHNOLOGY` (if I don't even put an HLS / Dash link)

We could use the progressive as that fallback, but instead we get an error message.

[This is a related issue](https://github.com/bitmovin/bitmovin-player-ui/issues/225)

**Comment by stevegeiger** [comment]
Closing this issue, as it is not relevant to our JS Encoding SDK. Taking the conversation over email instead.
