### ISSUE TITLE
403 forbidden error

### ISSUE THREAD

**Issue by ketz** [bitmovin/bitmovin-javascript#104]
I'm trying to run the [Dash on demand](https://github.com/bitmovin/bitmovin-javascript/blob/develop/examples/encoding/16_dash_on_demand.js) example with my api key and new inputs and outputs, but all I get is this:

> Unhandled rejection Error: HTTP Request was unsuccessful: HTTP Response Code was 403 Forbidden
    at new BitmovinError (/home/ubuntu/ibm/node_modules/bitmovin-javascript/dist/utils/BitmovinError.js:16:28)
    at /home/ubuntu/ibm/node_modules/bitmovin-javascript/dist/utils/http.js:42:23
    at process._tickCallback (internal/process/next_tick.js:103:7)

Any idea what could be causing it?

**Comment by LudoMichaud** [comment]
Hi @ketz 
I'm taking a look into this. 
As we already have another conversation together about this point, let me close this issue for now.
