### ISSUE TITLE
Api slow 

### ISSUE THREAD

**Issue by rbokel** [bitmovin/bitmovin-javascript#56]
Setting up my encoding  takes about 85 seconds. 
That seems to be quite a lot for an api, that more or less sets up some objects.  

While this pr helps a bit (down to 50 seconds)
https://github.com/bitmovin/bitmovin-javascript/pull/55
i wonder, if there is other things i can do to speed up the encoding configuration?

Is it good practice to recreate everything everytime when i want to encode something?
Or is there a way to set things up once and only change the input and output configuration?

**Comment by lukaskroepfl** [comment]
Hey!

> Is it good practice to recreate everything everytime when i want to encode something?

No, the examples are built this way so you can execute them without having to configure you codec configurations, inputs, outputs etc. by id. Resources that are not dependent on an encoding and it's id can and should be reused (have a look at our getting started guide where this is also described https://dashboard.bitmovin.com/getting-started/encoding/js/3)

**Comment by rbokel** [comment]
Hi Lukas, thanks for your help.     
 I've got one more question for you.     

My app is a client app, that potentially launches many encodings in parallel.     
Is it safe to re-use these objects from parallel running encodings ? 

Cheers,
Ralf

**Comment by lukaskroepfl** [comment]
Hi!

Yes inputs, outputs and codec configurations are safe to reuse among parallel running encodings.

Best, Lukas

**Comment by rbokel** [comment]
Hi there, i've noticed a major speed improvement at your end. 
Instead of 80 seconds my encoding only takes 10 seconds to setup now. 
Did you change anything?

**Comment by lukaskroepfl** [comment]
Hi, yes we did some optimizations at our end. We will also add the option to configure the http agent in the upcoming v2 release of the js client. Closing this issue, feel free to reopen if this problem comes up again.
