### ISSUE TITLE
Property 'list' does not exist on type 'object'.

### ISSUE THREAD

**Issue by josephlodero** [bitmovin/bitmovin-javascript#68]
![image](https://user-images.githubusercontent.com/11495107/42016869-a2f5a9e2-7adf-11e8-84aa-a9a5e76a2139.png)

Typescript Error
Property 'list' does not exist on type 'object'.

Im using ionic3

Thanks!

**Comment by lukaskroepfl** [comment]
Hey, thank you for flagging this. We're fixing it right now and will release a hotfix asap.

**Comment by lukaskroepfl** [comment]
Hey @josephlodero,  we just published version [2.1.2](https://www.npmjs.com/package/bitmovin-javascript/v/2.1.2) of the js client which should fix the TS error.
