### ISSUE TITLE
ionic3 about problem

### ISSUE THREAD

**Issue by sx844750857** [bitmovin/bitmovin-javascript#71]
java 后台传送一个byte数组的字节 比如byte [] b={5,9,5}.
ionic3, 用response.arrayBuffer接收的传过来的字节，ionic3 显示的是b=5,0,9,0,5 。为什么每一个字节后面会多出一个0？

**Comment by LudoMichaud** [comment]
Thank you very much for getting in contact. 
I'm afraid I can only provide support in English. Please feel free to send your question to support@bitmovin.com, we would then be happy to help you.
