### ISSUE TITLE
Expected 1 arguments, but got 0

### ISSUE THREAD

**Issue by josephlodero** [bitmovin/bitmovin-javascript#74]
Hi, can someone please help me with this error??

im following this example(https://github.com/bitmovin/bitmovin-javascript/blob/develop/examples/encoding/01_simple_encoding_dash_manifest.js)
its in the line 286 

![image](https://user-images.githubusercontent.com/11495107/43244247-a4e796c6-90dc-11e8-9618-f32720194fc9.png)

Thanks!

**Comment by lukaskroepfl** [comment]
Hey!
Thx for flagging, we'll have a look.

**Comment by Domysee** [comment]
Hi,

thanks for raising the issue, this is an error in the typing of our javascript library.
For now passing an empty object (`.start({})`) should fix it.

**Comment by Domysee** [comment]
Hi @josephlodero 

The warning is because `waitUntilEncodingFinished` rejects with `response.status`, which is not an `Error` object.
```
if (response.status === 'ERROR') {
  return reject(response.status);
}
```

Unfortunately I can't really help you figuring out why the encoding errors in the first place, for that please contact our [support](mailto:support@bitmovin.com).
