### ISSUE TITLE
v8.0 is not sending configured headers for license requests.

### ISSUE THREAD

**Issue by mhosman** [bitmovin/bitmovin-javascript#86]

**Comment by dweinber** [comment]
@mhosman I believe the reported issue is about the Bitmovin Web Player, right? This repository is about the Bitmovin API client, so I'll close this issue. Please send issues and feature requests to support@bitmovin.com.

By the way, did you check the v8 soon guide in our all-new documentation area at https://bitmovin.com/docs/player/tutorials/migration-guide-v7-to-v8? The addition of headers to requests was simplified from
```js
headers: [{
  name: ‘X-Custom-Header-Name’,
  value: ‘customHeaderValue’
}]
```
to 
```js
headers: {
  ‘X-Custom-Header-Name’: ‘customHeaderValue’
}
```
as outlined in the [last section](https://bitmovin.com/docs/player/tutorials/migration-guide-v7-to-v8#other-changes)

**Comment by mhosman** [comment]
Yes, I checked the docs for v8 and updated the headers to the new way. I'll send a mail. Thanks!
