### ISSUE TITLE
"MuxingInformation object for encoding with id '796bc5c8-7a30-491c-8354-3d35ba1b9129' and muxing with id '49e6a486-7e54-4539-bbd4-56827b1c6e57' is null!"

### ISSUE THREAD

**Issue by josephlodero** [bitmovin/bitmovin-javascript#92]
can someone please explain me with these error?? what does it mean by null??

**Comment by LudoMichaud** [comment]
hi @josephlodero,
Thanks for reaching out to us. 
Please could you get in contact with support@bitmovin.com and provide the above information again ?
We will then check  this accordingly and get back to you with more information. 
Thanks in advance
